#!/usr/bin/env python3
"""Scan generated Anvil region files (.mca) for target block IDs.

This is a lightweight, stdlib-only (struct + zlib) Minecraft Anvil region
reader. It does NOT fully parse NBT into a tree - it just decompresses each
chunk's raw NBT payload and searches for the UTF-8 bytes of the target block
resource-location strings (e.g. b"claudemod:prismium_ore"). Every NBT string
tag is stored as its raw UTF-8 payload immediately after a 2-byte big-endian
length prefix, with no other framing/escaping, so a substring match against
the decompressed bytes is a reliable, false-positive-resistant proxy for
"this resource location appears in this chunk's saved data (almost always
inside a block-state palette for an actually-placed block)" - without
needing a full NBT/anvil-parsing pip dependency (not guaranteed to be
installable in every environment this might run in, so intentionally
avoided).

Why this exists: GitHub issue #24 reports that Prismium ore cannot be found
in survival overworld. Code review of the worldgen JSON (configured_feature /
placed_feature / forge biome_modifier) found nothing obviously wrong, and the
existing CI "datapack validation" step (runGameTestServer) only proves the
registries *load*, not that the feature actually places blocks into real
generated terrain. This script closes that gap by scanning the region files
that runGameTestServer's headless dedicated server actually writes to disk
during its spawn-chunk-search startup sequence, giving empirical evidence
(not just "the JSON parses") of whether the ore feature is really placing
blocks. See PROGRESS.md for how this is wired into build-and-notify.yml.

Usage:
    python3 verify_ore_generation.py <region-dir> [target1 target2 ...]

Always exits 0 - this is a diagnostic tool, not a hard CI gate (a "not found"
result is not proof of absence; the number of chunks force-generated by a
headless server with zero connected players is unpredictable and may be
small). It prints a human-readable summary to stdout for the caller to save.
"""
import glob
import os
import struct
import sys
import zlib

DEFAULT_TARGETS = [
    b"claudemod:prismium_ore",
    b"claudemod:deepslate_prismium_ore",
]


def iter_chunks(region_path):
    """Yield (chunk_index, decompressed_nbt_bytes) for every populated chunk in a .mca file."""
    with open(region_path, "rb") as f:
        header = f.read(8192)
        if len(header) < 8192:
            return
        for i in range(1024):
            entry = header[i * 4:i * 4 + 4]
            offset_sectors = int.from_bytes(entry[0:3], "big")
            sector_count = entry[3]
            if offset_sectors == 0 or sector_count == 0:
                continue
            f.seek(offset_sectors * 4096)
            length_bytes = f.read(4)
            if len(length_bytes) < 4:
                continue
            length = struct.unpack(">I", length_bytes)[0]
            if length <= 1:
                continue
            compression_type_bytes = f.read(1)
            if not compression_type_bytes:
                continue
            compression_type = compression_type_bytes[0]
            payload = f.read(length - 1)
            try:
                if compression_type == 1:
                    data = zlib.decompress(payload, 16 + zlib.MAX_WBITS)  # gzip
                elif compression_type == 2:
                    data = zlib.decompress(payload)  # zlib (the common case)
                elif compression_type == 3:
                    data = payload  # uncompressed
                else:
                    continue
            except Exception:
                # Truncated/corrupt chunk (e.g. server killed mid-write) - skip it.
                continue
            yield i, data


def main():
    if len(sys.argv) < 2:
        print("usage: verify_ore_generation.py <region-dir> [target ...]")
        return 1
    region_dir = sys.argv[1]
    targets = [t.encode() for t in sys.argv[2:]] if len(sys.argv) > 2 else DEFAULT_TARGETS

    region_files = sorted(glob.glob(os.path.join(region_dir, "r.*.*.mca")))
    if not region_files:
        print(f"NO_REGION_FILES region_dir={region_dir}")
        return 0

    total_chunks_scanned = 0
    hits = {t: 0 for t in targets}
    hit_regions = {t: set() for t in targets}

    for region_path in region_files:
        for chunk_index, data in iter_chunks(region_path):
            total_chunks_scanned += 1
            for t in targets:
                if t in data:
                    hits[t] += 1
                    hit_regions[t].add(os.path.basename(region_path))

    print(f"region_dir={region_dir} region_files={len(region_files)} chunks_scanned={total_chunks_scanned}")
    for t in targets:
        name = t.decode()
        count = hits[t]
        regions = ",".join(sorted(hit_regions[t])) if hit_regions[t] else "-"
        verdict = "FOUND" if count > 0 else "NOT_FOUND"
        print(f"{verdict} {name}: chunks_with_hit={count} regions=[{regions}]")
    return 0


if __name__ == "__main__":
    sys.exit(main())
