package com.claudemod.entity;

import net.minecraft.util.RandomSource;
import net.minecraft.world.DifficultyInstance;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.ai.attributes.AttributeSupplier;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.entity.monster.Zombie;
import net.minecraft.world.level.Level;
import net.minecraft.sounds.SoundEvent;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.world.damagesource.DamageSource;
import org.jetbrains.annotations.Nullable;

/**
 * Prismium Deep Wraith - session 47, added directly at the repo owner's
 * request (interactive session, not a scheduled run): a Prismium Wraith
 * ({@link PrismiumWraithEntity}) left fully submerged for long enough was
 * converting into a plain vanilla {@code Drowned} (inherited, unmodified
 * {@code Zombie#doUnderWaterConversion}/{@code convertToZombieType}
 * behaviour - every {@code Zombie} subclass does this by default unless it
 * overrides that path). A reskinned vanilla Drowned breaks the mod's visual
 * identity, so this is a small dedicated entity that {@link
 * PrismiumWraithEntity#doUnderWaterConversion()} now redirects to instead.
 *
 * <p>Same "extend vanilla directly, minimise new AI/model risk" approach
 * PrismiumWraithEntity itself used for session 12 (see that class's
 * javadoc): this also extends {@link Zombie} rather than {@code Drowned},
 * reusing vanilla's {@code ZombieModel} for rendering (see {@link
 * com.claudemod.entity.client.PrismiumDeepWraithRenderer}) with only a new
 * texture swapped in (bluer "waterlogged basalt" body + green-tinted core
 * shard, generated by {@code scripts/textures/gen_prismium_deep_wraith.py},
 * deliberately keeping the same glowing-teal-crack family as the land
 * Wraith so the two read as the same creature in two states).
 *
 * <p>Behavioural deltas from a plain Zombie (and from
 * {@link PrismiumWraithEntity}):
 * <ul>
 *   <li>{@link #canBreatheUnderwater()} returns {@code true} so it never
 *   takes drowning damage and never itself tries to surface for air -
 *   without this it would just be a wraith that happens to be wet, still
 *   fighting the water instead of belonging in it.</li>
 *   <li>Slightly more health/less raw hit strength than the land Wraith
 *   (tuned as a "found you in your own territory" ambush threat rather
 *   than a straight upgrade - unverified in actual combat, first pass by
 *   feel only, see PROGRESS.md).</li>
 *   <li>Ambient/hurt/death sounds borrowed from vanilla's Guardian instead
 *   of the land Wraith's Vex sounds, for an "aquatic menace" register.</li>
 *   <li>Same no-default-equipment and stone-guardian silhouette choices as
 *   {@link PrismiumWraithEntity} (see that class's javadoc), for the same
 *   reasons.</li>
 * </ul>
 *
 * <p>Deliberately <b>not</b> given real smooth-swimming pathfinding (no
 * custom {@code MoveControl}/{@code PathNavigation} like vanilla's
 * {@code Drowned} has) - Zombie's default ground-based navigation can
 * already traverse underwater terrain (it just walks the seafloor rather
 * than swimming gracefully), and building a correct water-aware navigator
 * without being able to playtest it in this sandbox was judged too risky
 * for a first pass. Left as an explicit follow-up idea in PROGRESS.md.
 *
 * <p><b>Unverified</b>: like everything else in this mod, none of the
 * above (conversion redirect actually firing, underwater behaviour,
 * sounds, texture in-game) has been confirmed in a running client.
 */
public class PrismiumDeepWraithEntity extends Zombie {

    public PrismiumDeepWraithEntity(EntityType<? extends Zombie> entityType, Level level) {
        super(entityType, level);
    }

    public static AttributeSupplier.Builder createAttributes() {
        return Zombie.createAttributes()
                .add(Attributes.MAX_HEALTH, 34.0D)
                .add(Attributes.ATTACK_DAMAGE, 3.0D)
                .add(Attributes.ARMOR, 4.0D)
                .add(Attributes.MOVEMENT_SPEED, 0.23D)
                .add(Attributes.KNOCKBACK_RESISTANCE, 0.15D);
    }

    @Override
    public boolean canBreatheUnderwater() {
        return true;
    }

    /**
     * Root-cause fix for the repo owner's follow-up report that a Prismium
     * Wraith left in water "still" turns into a vanilla {@code Drowned}
     * (session 47's fix only redirected {@link PrismiumWraithEntity}'s own
     * water conversion to spawn a Deep Wraith instead - see that class's
     * {@code doUnderWaterConversion()} javadoc - but never touched this
     * class). Because {@code PrismiumDeepWraithEntity} also extends vanilla
     * {@link Zombie} and never overrode {@code convertsInWater()} or
     * {@code doUnderWaterConversion()} itself, it was fully subject to the
     * exact same inherited water-conversion timer as any other Zombie: after
     * ~600 ticks with its eye in fluid plus a further ~300-tick conversion
     * countdown, vanilla would call the *inherited* (unredirected)
     * {@code doUnderWaterConversion()} on the Deep Wraith and turn it into a
     * plain {@code EntityType.DROWNED} via {@code convertToZombieType}. Since
     * a Deep Wraith's entire habitat is underwater (that is the point of
     * this class), it was essentially guaranteed to eventually hit that
     * second, unhandled conversion - so "leave a Wraith in water" reliably
     * ended in a vanilla Drowned after two silent hops (Wraith to Deep
     * Wraith, then Deep Wraith to Drowned) instead of one, which is why the
     * original session 47 fix looked complete in code review but did not
     * actually resolve the reported symptom.
     *
     * Fix: override {@code convertsInWater()} to {@code false} so this class
     * never enters the water-conversion timer/state machine at all. This is
     * the terminal type in the chain (nothing should replace a Deep Wraith),
     * so cutting off conversion here rather than re-overriding
     * {@code doUnderWaterConversion()} again closes the loop for good instead
     * of just adding one more hop.
     * <b>Unverified</b>: cannot be confirmed in a running client from this
     * sandbox; if a Wraith is still observed becoming a vanilla Drowned
     * after this change, re-check whether any other code path independently
     * triggers a zombie-type conversion.
     */
    @Override
    protected boolean convertsInWater() {
        return false;
    }

    @Override
    protected void populateDefaultEquipmentSlots(RandomSource random, DifficultyInstance difficulty) {
        // See PrismiumWraithEntity#populateDefaultEquipmentSlots - same
        // "stay on-theme, no random vanilla gear" reasoning.
    }

    @Nullable
    @Override
    protected SoundEvent getAmbientSound() {
        return SoundEvents.GUARDIAN_AMBIENT;
    }

    @Nullable
    @Override
    protected SoundEvent getHurtSound(DamageSource damageSource) {
        return SoundEvents.GUARDIAN_HURT;
    }

    @Nullable
    @Override
    protected SoundEvent getDeathSound() {
        return SoundEvents.GUARDIAN_DEATH;
    }

    @Nullable
    @Override
    protected SoundEvent getStepSound() {
        return SoundEvents.WITHER_SKELETON_STEP;
    }
}
