package com.claudemod.gametest;

import com.claudemod.ClaudeMod;
import com.claudemod.blockentity.PrismiumCableBlockEntity;
import com.claudemod.blockentity.PrismiumCellBlockEntity;
import com.claudemod.blockentity.PrismiumGeneratorBlockEntity;
import com.claudemod.registry.ModBlocks;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraftforge.gametest.GameTestHolder;
import net.minecraftforge.gametest.PrefixGameTestTemplate;

/**
 * Automated GameTests for the Prismium Energy pillar (TODO11 in
 * PROGRESS.md: "GameTestフレームワークで、ContainerDataの同期を自動検証する
 * 仕組みを追加する"). Registered so CI's existing headless
 * {@code runGameTestServer} smoke test (see
 * {@code .github/workflows/build-and-notify.yml}'s "Validate
 * datapack/registries" step, which already boots this exact server -
 * previously with zero {@code @GameTest} methods to run) actually
 * exercises this mod's own logic on every push, not just registry
 * loading.
 *
 * <p><b>Why this exists:</b> GitHub issue #15 reported (among other
 * things) two very concrete, very testable claims about Prismium Energy:
 * "セルを発電機の隣に置いた際、2倍の量貯蓄されるバグ" (a Cell ends up with
 * double the FE a Generator actually produced) and "ケーブルが隣接する6
 * 方向にしか影響しないバグ" (a cable can't relay energy more than one hop).
 * Both were addressed by code changes in earlier sessions (see
 * PROGRESS.md section 1, "Git/push運用" history and
 * {@link com.claudemod.energy.EnergyPushHelper#pushThroughNetwork}'s own
 * doc) but - like literally everything else in this mod (see PROGRESS.md
 * section 3's standing note) - never verified in an actual running game,
 * because this sandbox cannot launch a client. A GameTest is the one
 * kind of "real game" verification this sandbox *can* run: CI's own
 * {@code gameTestServer} boots an actual headless dedicated server (same
 * registry/tick code path a player's world uses) and this class's tests
 * run inside it automatically on every push, failing the build (exit
 * code = number of failed required tests, per Forge's own GameTest docs)
 * if either of those two behaviors ever regresses.
 *
 * <p><b>What this does NOT cover:</b> the specific client-side
 * {@code ContainerData} bug fixed in session #84 (see
 * {@link com.claudemod.menu.PrismiumGeneratorMenu#resolveData}'s doc) was
 * a bug in the *client's own menu factory* reusing a live block entity's
 * dummy-set()-only ContainerData instead of a fresh
 * {@code SimpleContainerData} - GameTestServer has no connected client at
 * all, so there is no client-side menu construction happening here to
 * exercise. What these tests verify instead is the *server-side* half of
 * that same sync path: that {@link PrismiumGeneratorBlockEntity#getContainerData()}
 * (the real instance {@code ClientboundContainerSetDataPacket} payloads
 * are computed from every tick, see {@code AbstractContainerMenu#broadcastChanges})
 * actually mirrors the block entity's live fields rather than silently
 * drifting - i.e. "if a future session adds a new gauge and forgets to
 * wire it into {@code get(int)}, or breaks the existing wiring, this
 * fails" - a narrower but still real slice of "did we break the sync
 * plumbing", automatically checked without needing a client.
 *
 * <p>Uses a single shared, entirely-air structure template
 * ({@code data/claudemod/structures/gametest/empty_platform.nbt}, 9x5x9,
 * generated by a one-off Python/nbtlib script - see PROGRESS.md) as a
 * bounding box; every block placed inside it is set directly via
 * {@link GameTestHelper#setBlock} rather than baked into the structure,
 * so the same template can be reused by any future test in this class
 * without needing a new hand-crafted .nbt per test.
 */
@GameTestHolder(value = ClaudeMod.MOD_ID, namespace = ClaudeMod.MOD_ID)
@PrefixGameTestTemplate(false)
public class ClaudeModGameTests {

    private static final String EMPTY_PLATFORM_TEMPLATE = "gametest/empty_platform";

    /** FE this test's two-cable network should have moved from the
     * Generator to the Cell after {@link #CHECK_DELAY_TICKS} ticks of
     * uninterrupted burning, assuming the fix in
     * {@link com.claudemod.energy.EnergyPushHelper#pushThroughNetwork} is
     * intact: {@code CHECK_DELAY_TICKS * GENERATION_PER_TICK}. Bounds
     * below intentionally leave a few ticks of slack either side rather
     * than asserting this exact value, since GameTest's own scheduled-
     * callback tick and this mod's block entity tickers are not
     * guaranteed to interleave with zero ambiguity (see class doc) - the
     * slack is small enough that it cannot mask the specific regressions
     * this test exists to catch (a total no-transfer failure, or a ~2x
     * duplication bug), both of which land far outside these bounds.
     */
    private static final int CHECK_DELAY_TICKS = 30;
    private static final int EXPECTED_MIN_TOTAL_FE = 200; // >= 20 ticks worth
    private static final int EXPECTED_MAX_TOTAL_FE = 310; // <= 31 ticks worth; a 2x-duplication bug would read ~600

    /**
     * Regression test for GitHub issue #15's "ケーブルが隣接する6方向にしか
     * 影響しない" report and its "2倍の量貯蓄される" report, combined: a
     * Generator, two Prismium Cables, and a Cell are placed in a straight
     * line (Cell is three blocks from the Generator - not a direct
     * neighbor, so a regression back to "pushToNeighbors only" would
     * leave the Cell at 0 forever and time this test out) and fed one
     * shard's worth of burn time directly. After {@link #CHECK_DELAY_TICKS}
     * ticks, the Cell must have received a strictly positive amount of FE
     * (catches the "can't relay past one hop" regression) and the total
     * FE now sitting anywhere in the network (Generator + both cables +
     * Cell) must fall within a tight, deterministic band based on
     * {@link PrismiumGeneratorBlockEntity#GENERATION_PER_TICK} (catches a
     * duplication regression - a real conservation bug would either
     * overshoot this band by roughly 2x, or every FE would simply vanish,
     * undershooting it to near zero).
     */
    @GameTest(template = EMPTY_PLATFORM_TEMPLATE, templateNamespace = ClaudeMod.MOD_ID,
            timeoutTicks = CHECK_DELAY_TICKS + 20)
    public static void energyFlowsThroughCableNetwork(GameTestHelper helper) {
        BlockPos generatorPos = new BlockPos(1, 1, 1);
        BlockPos cable1Pos = new BlockPos(2, 1, 1);
        BlockPos cable2Pos = new BlockPos(3, 1, 1);
        BlockPos cellPos = new BlockPos(4, 1, 1);

        helper.setBlock(generatorPos, ModBlocks.PRISMIUM_GENERATOR.get());
        helper.setBlock(cable1Pos, ModBlocks.PRISMIUM_CABLE.get());
        helper.setBlock(cable2Pos, ModBlocks.PRISMIUM_CABLE.get());
        helper.setBlock(cellPos, ModBlocks.PRISMIUM_CELL.get());

        if (!(helper.getBlockEntity(generatorPos) instanceof PrismiumGeneratorBlockEntity generator)) {
            helper.fail("Generator block entity was not created", generatorPos);
            return;
        }
        // One shard's worth of burn time (1600 ticks, see
        // PrismiumGeneratorBlockEntity#BURN_TIME_PER_SHARD) - comfortably
        // more than CHECK_DELAY_TICKS, so the generator is burning for
        // this test's entire duration and GENERATION_PER_TICK stays
        // constant throughout.
        generator.addFuel();

        helper.runAfterDelay(CHECK_DELAY_TICKS, () -> {
            if (!(helper.getBlockEntity(cable1Pos) instanceof PrismiumCableBlockEntity cable1)
                    || !(helper.getBlockEntity(cable2Pos) instanceof PrismiumCableBlockEntity cable2)
                    || !(helper.getBlockEntity(cellPos) instanceof PrismiumCellBlockEntity cell)) {
                helper.fail("A cable or the cell block entity was not created", cellPos);
                return;
            }

            int cellEnergy = cell.getEnergyStorage().getEnergyStored();
            helper.assertTrue(cellEnergy > 0,
                    "Cell received no FE at all through the two-cable network (cable relay regression?) - cellEnergy="
                            + cellEnergy);

            int totalFe = generator.getEnergyStorage().getEnergyStored()
                    + cable1.getEnergyStorage().getEnergyStored()
                    + cable2.getEnergyStorage().getEnergyStored()
                    + cellEnergy;
            helper.assertTrue(totalFe >= EXPECTED_MIN_TOTAL_FE && totalFe <= EXPECTED_MAX_TOTAL_FE,
                    "Total FE across generator+cables+cell was " + totalFe + ", expected between "
                            + EXPECTED_MIN_TOTAL_FE + " and " + EXPECTED_MAX_TOTAL_FE
                            + " (outside this band means either FE is disappearing or being duplicated)");

            helper.succeed();
        });
    }

    /**
     * Regression test for the class of bug session #84 fixed on the
     * client side (see {@link com.claudemod.menu.PrismiumGeneratorMenu}'s
     * doc): verifies the *server-side* {@code ContainerData} instance
     * that feeds every GUI sync packet
     * ({@link PrismiumGeneratorBlockEntity#getContainerData()}) actually
     * tracks the block entity's live energy fields instead of silently
     * drifting or being left unwired. Places a lone Generator, feeds it
     * fuel, and after a short delay asserts the energy/max-energy slots
     * read through {@code getContainerData()} exactly match the live
     * {@link com.claudemod.energy.PrismiumEnergyStorage} getters at that
     * same instant (no tick-timing slack needed for this part - both
     * sides are read from the same object at the same moment) and that a
     * strictly positive amount was actually generated in the meantime
     * (guards against a false pass where both sides are wired but
     * generation itself silently stopped).
     */
    @GameTest(template = EMPTY_PLATFORM_TEMPLATE, templateNamespace = ClaudeMod.MOD_ID, timeoutTicks = 40)
    public static void generatorContainerDataTracksLiveEnergy(GameTestHelper helper) {
        BlockPos generatorPos = new BlockPos(1, 1, 1);
        helper.setBlock(generatorPos, ModBlocks.PRISMIUM_GENERATOR.get());

        if (!(helper.getBlockEntity(generatorPos) instanceof PrismiumGeneratorBlockEntity generator)) {
            helper.fail("Generator block entity was not created", generatorPos);
            return;
        }
        generator.addFuel();

        helper.runAfterDelay(15, () -> {
            int liveEnergy = generator.getEnergyStorage().getEnergyStored();
            int liveMax = generator.getEnergyStorage().getMaxEnergyStored();
            var containerData = generator.getContainerData();

            helper.assertTrue(liveEnergy > 0,
                    "Generator had generated no FE at all after 15 ticks of burning - generation itself appears broken, unrelated to sync");
            helper.assertTrue(containerData.get(0) == liveEnergy,
                    "ContainerData slot 0 (energy) was " + containerData.get(0)
                            + " but the live energy storage reads " + liveEnergy + " - sync wiring is broken");
            helper.assertTrue(containerData.get(1) == liveMax,
                    "ContainerData slot 1 (max energy) was " + containerData.get(1)
                            + " but the live energy storage reads " + liveMax + " - sync wiring is broken");

            helper.succeed();
        });
    }
}
