package com.claudemod.gametest;

import com.claudemod.ClaudeMod;
import com.claudemod.blockentity.AbstractPrismiumMachineBlockEntity;
import com.claudemod.blockentity.PrismiumCableBlockEntity;
import com.claudemod.blockentity.PrismiumCellBlockEntity;
import com.claudemod.blockentity.PrismiumCompressorBlockEntity;
import com.claudemod.blockentity.PrismiumGeneratorBlockEntity;
import com.claudemod.blockentity.PrismiumPulverizerBlockEntity;
import com.claudemod.blockentity.PrismiumPylonBlockEntity;
import com.claudemod.blockentity.PrismiumRestorerBlockEntity;
import com.claudemod.blockentity.PrismiumSmelterBlockEntity;
import com.claudemod.blockentity.PrismiumWardstoneBlockEntity;
import com.claudemod.registry.ModBlocks;
import com.claudemod.registry.ModItems;
import net.minecraft.core.BlockPos;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.world.inventory.ContainerData;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.gametest.GameTestHolder;
import net.minecraftforge.gametest.PrefixGameTestTemplate;

/**
 * Automated GameTests for the Prismium Energy pillar (TODO11 in
 * PROGRESS.md: "GameTestフレームワークで、ContainerDataの同期を自動検証する
 * 仕組みを追加する"). Registered so CI's existing headless
 * {@code runGameTestServer} smoke test (see
 * {@code .github/workflows/build-and-notify.yml}'s "Validate
 * datapack/registries" step, which already boots this exact server -
 * previously with zero {@code @GameTest} methods to run) actually
 * exercises this mod's own logic on every push, not just registry
 * loading.
 *
 * <p><b>Why this exists:</b> GitHub issue #15 reported (among other
 * things) two very concrete, very testable claims about Prismium Energy:
 * "セルを発電機の隣に置いた際、2倍の量貯蓄されるバグ" (a Cell ends up with
 * double the FE a Generator actually produced) and "ケーブルが隣接する6
 * 方向にしか影響しないバグ" (a cable can't relay energy more than one hop).
 * Both were addressed by code changes in earlier sessions (see
 * PROGRESS.md section 1, "Git/push運用" history and
 * {@link com.claudemod.energy.EnergyPushHelper#pushThroughNetwork}'s own
 * doc) but - like literally everything else in this mod (see PROGRESS.md
 * section 3's standing note) - never verified in an actual running game,
 * because this sandbox cannot launch a client. A GameTest is the one
 * kind of "real game" verification this sandbox *can* run: CI's own
 * {@code gameTestServer} boots an actual headless dedicated server (same
 * registry/tick code path a player's world uses) and this class's tests
 * run inside it automatically on every push, failing the build (exit
 * code = number of failed required tests, per Forge's own GameTest docs)
 * if either of those two behaviors ever regresses.
 *
 * <p><b>What this does NOT cover:</b> the specific client-side
 * {@code ContainerData} bug fixed in session #84 (see
 * {@link com.claudemod.menu.PrismiumGeneratorMenu#resolveData}'s doc) was
 * a bug in the *client's own menu factory* reusing a live block entity's
 * dummy-set()-only ContainerData instead of a fresh
 * {@code SimpleContainerData} - GameTestServer has no connected client at
 * all, so there is no client-side menu construction happening here to
 * exercise. What these tests verify instead is the *server-side* half of
 * that same sync path: that {@link PrismiumGeneratorBlockEntity#getContainerData()}
 * (the real instance {@code ClientboundContainerSetDataPacket} payloads
 * are computed from every tick, see {@code AbstractContainerMenu#broadcastChanges})
 * actually mirrors the block entity's live fields rather than silently
 * drifting - i.e. "if a future session adds a new gauge and forgets to
 * wire it into {@code get(int)}, or breaks the existing wiring, this
 * fails" - a narrower but still real slice of "did we break the sync
 * plumbing", automatically checked without needing a client.
 *
 * <p>Uses a single shared, entirely-air structure template
 * ({@code data/claudemod/structures/gametest/empty_platform.nbt}, 9x5x9,
 * generated by a one-off Python/nbtlib script - see PROGRESS.md) as a
 * bounding box; every block placed inside it is set directly via
 * {@link GameTestHelper#setBlock} rather than baked into the structure,
 * so the same template can be reused by any future test in this class
 * without needing a new hand-crafted .nbt per test.
 */
// Forge 47.4.0 (pinned by this project)'s GameTestHolder only has a
// single value() (the default template namespace, "minecraft" if
// omitted) - no separate namespace() attribute (that was added in a
// later Forge release; confirmed against the actual
// MinecraftForge/MinecraftForge "1.20.1" branch source, not a newer
// mismatched doc - see class doc). Every @GameTest below also sets
// templateNamespace explicitly, so this value is only a fallback.
@GameTestHolder(ClaudeMod.MOD_ID)
@PrefixGameTestTemplate(false)
public class ClaudeModGameTests {

    private static final String EMPTY_PLATFORM_TEMPLATE = "gametest/empty_platform";

    /** FE this test's two-cable network should have moved from the
     * Generator to the Cell after {@link #CHECK_DELAY_TICKS} ticks of
     * uninterrupted burning, assuming the fix in
     * {@link com.claudemod.energy.EnergyPushHelper#pushThroughNetwork} is
     * intact: {@code CHECK_DELAY_TICKS * GENERATION_PER_TICK}. Bounds
     * below intentionally leave a few ticks of slack either side rather
     * than asserting this exact value, since GameTest's own scheduled-
     * callback tick and this mod's block entity tickers are not
     * guaranteed to interleave with zero ambiguity (see class doc) - the
     * slack is small enough that it cannot mask the specific regressions
     * this test exists to catch (a total no-transfer failure, or a ~2x
     * duplication bug), both of which land far outside these bounds.
     */
    private static final int CHECK_DELAY_TICKS = 30;
    private static final int EXPECTED_MIN_TOTAL_FE = 200; // >= 20 ticks worth
    private static final int EXPECTED_MAX_TOTAL_FE = 310; // <= 31 ticks worth; a 2x-duplication bug would read ~600

    /**
     * Regression test for GitHub issue #15's "ケーブルが隣接する6方向にしか
     * 影響しない" report and its "2倍の量貯蓄される" report, combined: a
     * Generator, two Prismium Cables, and a Cell are placed in a straight
     * line (Cell is three blocks from the Generator - not a direct
     * neighbor, so a regression back to "pushToNeighbors only" would
     * leave the Cell at 0 forever and time this test out) and fed one
     * shard's worth of burn time directly. After {@link #CHECK_DELAY_TICKS}
     * ticks, the Cell must have received a strictly positive amount of FE
     * (catches the "can't relay past one hop" regression) and the total
     * FE now sitting anywhere in the network (Generator + both cables +
     * Cell) must fall within a tight, deterministic band based on
     * {@link PrismiumGeneratorBlockEntity#GENERATION_PER_TICK} (catches a
     * duplication regression - a real conservation bug would either
     * overshoot this band by roughly 2x, or every FE would simply vanish,
     * undershooting it to near zero).
     */
    @GameTest(template = EMPTY_PLATFORM_TEMPLATE, templateNamespace = ClaudeMod.MOD_ID,
            timeoutTicks = CHECK_DELAY_TICKS + 20)
    public static void energyFlowsThroughCableNetwork(GameTestHelper helper) {
        BlockPos generatorPos = new BlockPos(1, 1, 1);
        BlockPos cable1Pos = new BlockPos(2, 1, 1);
        BlockPos cable2Pos = new BlockPos(3, 1, 1);
        BlockPos cellPos = new BlockPos(4, 1, 1);

        helper.setBlock(generatorPos, ModBlocks.PRISMIUM_GENERATOR.get());
        helper.setBlock(cable1Pos, ModBlocks.PRISMIUM_CABLE.get());
        helper.setBlock(cable2Pos, ModBlocks.PRISMIUM_CABLE.get());
        helper.setBlock(cellPos, ModBlocks.PRISMIUM_CELL.get());

        if (!(helper.getBlockEntity(generatorPos) instanceof PrismiumGeneratorBlockEntity generator)) {
            helper.fail("Generator block entity was not created", generatorPos);
            return;
        }
        // One shard's worth of burn time (1600 ticks, see
        // PrismiumGeneratorBlockEntity#BURN_TIME_PER_SHARD) - comfortably
        // more than CHECK_DELAY_TICKS, so the generator is burning for
        // this test's entire duration and GENERATION_PER_TICK stays
        // constant throughout.
        generator.addFuel();

        helper.runAfterDelay(CHECK_DELAY_TICKS, () -> {
            if (!(helper.getBlockEntity(cable1Pos) instanceof PrismiumCableBlockEntity cable1)
                    || !(helper.getBlockEntity(cable2Pos) instanceof PrismiumCableBlockEntity cable2)
                    || !(helper.getBlockEntity(cellPos) instanceof PrismiumCellBlockEntity cell)) {
                helper.fail("A cable or the cell block entity was not created", cellPos);
                return;
            }

            int cellEnergy = cell.getEnergyStorage().getEnergyStored();
            helper.assertTrue(cellEnergy > 0,
                    "Cell received no FE at all through the two-cable network (cable relay regression?) - cellEnergy="
                            + cellEnergy);

            int totalFe = generator.getEnergyStorage().getEnergyStored()
                    + cable1.getEnergyStorage().getEnergyStored()
                    + cable2.getEnergyStorage().getEnergyStored()
                    + cellEnergy;
            helper.assertTrue(totalFe >= EXPECTED_MIN_TOTAL_FE && totalFe <= EXPECTED_MAX_TOTAL_FE,
                    "Total FE across generator+cables+cell was " + totalFe + ", expected between "
                            + EXPECTED_MIN_TOTAL_FE + " and " + EXPECTED_MAX_TOTAL_FE
                            + " (outside this band means either FE is disappearing or being duplicated)");

            helper.succeed();
        });
    }

    /**
     * Regression test for the class of bug session #84 fixed on the
     * client side (see {@link com.claudemod.menu.PrismiumGeneratorMenu}'s
     * doc): verifies the *server-side* {@code ContainerData} instance
     * that feeds every GUI sync packet
     * ({@link PrismiumGeneratorBlockEntity#getContainerData()}) actually
     * tracks the block entity's live energy fields instead of silently
     * drifting or being left unwired. Places a lone Generator, feeds it
     * fuel, and after a short delay asserts the energy/max-energy slots
     * read through {@code getContainerData()} exactly match the live
     * {@link com.claudemod.energy.PrismiumEnergyStorage} getters at that
     * same instant (no tick-timing slack needed for this part - both
     * sides are read from the same object at the same moment) and that a
     * strictly positive amount was actually generated in the meantime
     * (guards against a false pass where both sides are wired but
     * generation itself silently stopped).
     */
    @GameTest(template = EMPTY_PLATFORM_TEMPLATE, templateNamespace = ClaudeMod.MOD_ID, timeoutTicks = 40)
    public static void generatorContainerDataTracksLiveEnergy(GameTestHelper helper) {
        BlockPos generatorPos = new BlockPos(1, 1, 1);
        helper.setBlock(generatorPos, ModBlocks.PRISMIUM_GENERATOR.get());

        if (!(helper.getBlockEntity(generatorPos) instanceof PrismiumGeneratorBlockEntity generator)) {
            helper.fail("Generator block entity was not created", generatorPos);
            return;
        }
        generator.addFuel();

        helper.runAfterDelay(15, () -> {
            int liveEnergy = generator.getEnergyStorage().getEnergyStored();
            int liveMax = generator.getEnergyStorage().getMaxEnergyStored();
            var containerData = generator.getContainerData();

            helper.assertTrue(liveEnergy > 0,
                    "Generator had generated no FE at all after 15 ticks of burning - generation itself appears broken, unrelated to sync");
            helper.assertTrue(containerData.get(0) == liveEnergy,
                    "ContainerData slot 0 (energy) was " + containerData.get(0)
                            + " but the live energy storage reads " + liveEnergy + " - sync wiring is broken");
            helper.assertTrue(containerData.get(1) == liveMax,
                    "ContainerData slot 1 (max energy) was " + containerData.get(1)
                            + " but the live energy storage reads " + liveMax + " - sync wiring is broken");

            helper.succeed();
        });
    }

    /** FE injected directly via {@code receiveEnergy} in the sink-block
     * ContainerData tests below - well under every sink block's
     * MAX_RECEIVE (2,000) and CAPACITY (4,000), see each block entity's
     * own constants. */
    private static final int SINK_TEST_FE = 500;

    /** Ticks to wait before checking progress in the three
     * {@code *ProgressAdvancesWhileProcessing} tests below - deliberately
     * well under {@link AbstractPrismiumMachineBlockEntity#PROCESS_TIME_TICKS}
     * (100) so the operation is still in flight (input not yet consumed,
     * output slot still empty) when the assertion runs, and well under
     * what {@link AbstractPrismiumMachineBlockEntity#CAPACITY} worth of
     * energy (set directly via {@code setEnergy} before the delay) could
     * ever run out from at {@link AbstractPrismiumMachineBlockEntity#ENERGY_PER_TICK}
     * per tick (4,000 / 20 = 200 ticks worth), so a stalled-for-energy
     * false failure is not possible here. */
    private static final int PROGRESS_CHECK_DELAY_TICKS = 10;
    /** Slack ticks allowed below {@link #PROGRESS_CHECK_DELAY_TICKS} when
     * asserting the live progress counter - GameTest's own scheduled
     * callback and this mod's block entity ticker are not guaranteed to
     * interleave with zero ambiguity (see this class's top-level doc), so
     * progress landing a tick or two short of the wall-clock delay is
     * expected and not itself a regression. Progress can never read
     * *above* {@link #PROGRESS_CHECK_DELAY_TICKS} (it increments by
     * exactly 1 per tick while active, see {@link
     * AbstractPrismiumMachineBlockEntity#tick}), so no slack is allowed on
     * that side - any overshoot would mean progress is incrementing more
     * than once per tick, a real bug this test should catch. */
    private static final int PROGRESS_CHECK_SLACK_TICKS = 2;

    /**
     * Regression tests mirroring {@link #generatorContainerDataTracksLiveEnergy}
     * for the mod's other energy-consuming GUIs (TODO11 in PROGRESS.md's
     * "次にやるべき拡張": "他の機械(Pylon/Restorer/Wardstone/Pulverizer/
     * Smelter/Compressor)のContainerData同期テストへの横展開"). This is the
     * same server-side half of the session #84 sync bug (see this class's
     * own top-level doc) checked for every remaining GUI block in the mod,
     * closing the gap left by only covering Generator.
     *
     * <p>Generator is the only block in the mod that generates its own FE
     * over time, which is why its test above feeds fuel and waits several
     * ticks. Every block covered below (Pylon, Restorer, Wardstone,
     * Pulverizer, Smelter, Compressor) is instead a pure energy sink
     * (maxExtract == 0, confirmed in each block entity's own class doc) -
     * the only way any of them gain FE is a {@code receiveEnergy} call,
     * exactly what a neighboring cable's push performs (see
     * {@link com.claudemod.energy.EnergyPushHelper#pushThroughNetwork}).
     * So these tests skip the cable network entirely and call
     * {@code receiveEnergy} directly on the block entity's own energy
     * storage - functionally identical from the block's point of view -
     * then assert the read-only {@link ContainerData} exposed to the
     * client mirrors the live storage in that same instant (no tick delay
     * needed, unlike the generation-based test above: both reads happen
     * synchronously here).
     */
    @GameTest(template = EMPTY_PLATFORM_TEMPLATE, templateNamespace = ClaudeMod.MOD_ID, timeoutTicks = 20)
    public static void pylonContainerDataTracksLiveEnergy(GameTestHelper helper) {
        BlockPos pos = new BlockPos(1, 1, 1);
        helper.setBlock(pos, ModBlocks.PRISMIUM_PYLON.get());

        if (!(helper.getBlockEntity(pos) instanceof PrismiumPylonBlockEntity pylon)) {
            helper.fail("Pylon block entity was not created", pos);
            return;
        }

        int accepted = pylon.getEnergyStorage().receiveEnergy(SINK_TEST_FE, false);
        helper.assertTrue(accepted > 0,
                "Pylon rejected all injected FE - receiveEnergy itself appears broken, unrelated to sync");

        ContainerData containerData = pylon.getContainerData();
        int liveEnergy = pylon.getEnergyStorage().getEnergyStored();
        int liveMax = pylon.getEnergyStorage().getMaxEnergyStored();
        helper.assertTrue(containerData.get(0) == liveEnergy,
                "Pylon ContainerData slot 0 (energy) was " + containerData.get(0)
                        + " but the live energy storage reads " + liveEnergy + " - sync wiring is broken");
        helper.assertTrue(containerData.get(1) == liveMax,
                "Pylon ContainerData slot 1 (max energy) was " + containerData.get(1)
                        + " but the live energy storage reads " + liveMax + " - sync wiring is broken");

        helper.succeed();
    }

    @GameTest(template = EMPTY_PLATFORM_TEMPLATE, templateNamespace = ClaudeMod.MOD_ID, timeoutTicks = 20)
    public static void restorerContainerDataTracksLiveEnergy(GameTestHelper helper) {
        BlockPos pos = new BlockPos(1, 1, 1);
        helper.setBlock(pos, ModBlocks.PRISMIUM_RESTORER.get());

        if (!(helper.getBlockEntity(pos) instanceof PrismiumRestorerBlockEntity restorer)) {
            helper.fail("Restorer block entity was not created", pos);
            return;
        }

        int accepted = restorer.getEnergyStorage().receiveEnergy(SINK_TEST_FE, false);
        helper.assertTrue(accepted > 0,
                "Restorer rejected all injected FE - receiveEnergy itself appears broken, unrelated to sync");

        ContainerData containerData = restorer.getContainerData();
        int liveEnergy = restorer.getEnergyStorage().getEnergyStored();
        int liveMax = restorer.getEnergyStorage().getMaxEnergyStored();
        helper.assertTrue(containerData.get(0) == liveEnergy,
                "Restorer ContainerData slot 0 (energy) was " + containerData.get(0)
                        + " but the live energy storage reads " + liveEnergy + " - sync wiring is broken");
        helper.assertTrue(containerData.get(1) == liveMax,
                "Restorer ContainerData slot 1 (max energy) was " + containerData.get(1)
                        + " but the live energy storage reads " + liveMax + " - sync wiring is broken");

        helper.succeed();
    }

    @GameTest(template = EMPTY_PLATFORM_TEMPLATE, templateNamespace = ClaudeMod.MOD_ID, timeoutTicks = 20)
    public static void wardstoneContainerDataTracksLiveEnergy(GameTestHelper helper) {
        BlockPos pos = new BlockPos(1, 1, 1);
        helper.setBlock(pos, ModBlocks.PRISMIUM_WARDSTONE.get());

        if (!(helper.getBlockEntity(pos) instanceof PrismiumWardstoneBlockEntity wardstone)) {
            helper.fail("Wardstone block entity was not created", pos);
            return;
        }

        int accepted = wardstone.getEnergyStorage().receiveEnergy(SINK_TEST_FE, false);
        helper.assertTrue(accepted > 0,
                "Wardstone rejected all injected FE - receiveEnergy itself appears broken, unrelated to sync");

        ContainerData containerData = wardstone.getContainerData();
        int liveEnergy = wardstone.getEnergyStorage().getEnergyStored();
        int liveMax = wardstone.getEnergyStorage().getMaxEnergyStored();
        helper.assertTrue(containerData.get(0) == liveEnergy,
                "Wardstone ContainerData slot 0 (energy) was " + containerData.get(0)
                        + " but the live energy storage reads " + liveEnergy + " - sync wiring is broken");
        helper.assertTrue(containerData.get(1) == liveMax,
                "Wardstone ContainerData slot 1 (max energy) was " + containerData.get(1)
                        + " but the live energy storage reads " + liveMax + " - sync wiring is broken");

        helper.succeed();
    }

    @GameTest(template = EMPTY_PLATFORM_TEMPLATE, templateNamespace = ClaudeMod.MOD_ID, timeoutTicks = 20)
    public static void pulverizerContainerDataTracksLiveEnergy(GameTestHelper helper) {
        BlockPos pos = new BlockPos(1, 1, 1);
        helper.setBlock(pos, ModBlocks.PRISMIUM_PULVERIZER.get());

        if (!(helper.getBlockEntity(pos) instanceof PrismiumPulverizerBlockEntity pulverizer)) {
            helper.fail("Pulverizer block entity was not created", pos);
            return;
        }

        assertMachineContainerDataTracksLiveEnergy(helper, pulverizer.getEnergyStorage(),
                pulverizer.getContainerData(), "Pulverizer");
        helper.succeed();
    }

    @GameTest(template = EMPTY_PLATFORM_TEMPLATE, templateNamespace = ClaudeMod.MOD_ID, timeoutTicks = 20)
    public static void smelterContainerDataTracksLiveEnergy(GameTestHelper helper) {
        BlockPos pos = new BlockPos(1, 1, 1);
        helper.setBlock(pos, ModBlocks.PRISMIUM_SMELTER.get());

        if (!(helper.getBlockEntity(pos) instanceof PrismiumSmelterBlockEntity smelter)) {
            helper.fail("Smelter block entity was not created", pos);
            return;
        }

        assertMachineContainerDataTracksLiveEnergy(helper, smelter.getEnergyStorage(),
                smelter.getContainerData(), "Smelter");
        helper.succeed();
    }

    @GameTest(template = EMPTY_PLATFORM_TEMPLATE, templateNamespace = ClaudeMod.MOD_ID, timeoutTicks = 20)
    public static void compressorContainerDataTracksLiveEnergy(GameTestHelper helper) {
        BlockPos pos = new BlockPos(1, 1, 1);
        helper.setBlock(pos, ModBlocks.PRISMIUM_COMPRESSOR.get());

        if (!(helper.getBlockEntity(pos) instanceof PrismiumCompressorBlockEntity compressor)) {
            helper.fail("Compressor block entity was not created", pos);
            return;
        }

        assertMachineContainerDataTracksLiveEnergy(helper, compressor.getEnergyStorage(),
                compressor.getContainerData(), "Compressor");
        helper.succeed();
    }

    /**
     * Shared assertion body for the three {@code AbstractPrismiumMachineBlockEntity}
     * subclasses (Pulverizer/Smelter/Compressor), which all share byte-
     * identical energy storage and {@link ContainerData} wiring (see that
     * base class's own doc, session #77's extraction). Injects
     * {@link #SINK_TEST_FE} directly via {@code receiveEnergy} (same
     * reasoning as the Pylon/Restorer/Wardstone tests above) and checks
     * slots 0/1 (energy/max energy). Slots 2/3 (progress/active) are
     * intentionally not asserted here - reaching a non-zero, deterministic
     * progress value needs a valid queued recipe and several ticks of
     * processing, which is a meaningfully different (and already
     * indirectly exercised by the recipe tables' own existence) scenario
     * from "is the sync wiring for the energy bars connected at all";
     * kept separate to avoid this test depending on any one machine's
     * specific hardcoded recipe table.
     */
    private static void assertMachineContainerDataTracksLiveEnergy(GameTestHelper helper,
            com.claudemod.energy.PrismiumEnergyStorage energyStorage, ContainerData containerData, String label) {
        int accepted = energyStorage.receiveEnergy(SINK_TEST_FE, false);
        helper.assertTrue(accepted > 0,
                label + " rejected all injected FE - receiveEnergy itself appears broken, unrelated to sync");

        int liveEnergy = energyStorage.getEnergyStored();
        int liveMax = energyStorage.getMaxEnergyStored();
        helper.assertTrue(containerData.get(0) == liveEnergy,
                label + " ContainerData slot 0 (energy) was " + containerData.get(0)
                        + " but the live energy storage reads " + liveEnergy + " - sync wiring is broken");
        helper.assertTrue(containerData.get(1) == liveMax,
                label + " ContainerData slot 1 (max energy) was " + containerData.get(1)
                        + " but the live energy storage reads " + liveMax + " - sync wiring is broken");
    }

    /**
     * TODO11's remaining "次にやるべき拡張(c)" item: unlike {@link
     * #assertMachineContainerDataTracksLiveEnergy} above (which
     * deliberately skips slots 2/3, see that method's doc), these three
     * tests queue an actual valid recipe (a real input item this
     * machine's own hardcoded {@code recipeFor} table accepts, at exactly
     * the count {@code inputCountPerOperation()} needs - the many-to-one
     * count for Smelter/Compressor, or 1 for Pulverizer's default) with
     * energy topped up to full via {@link
     * com.claudemod.energy.PrismiumEnergyStorage#setEnergy} (same NBT-
     * restore-only method {@code PrismiumCellBlockEntity} already uses
     * elsewhere in this mod - directly setting the stored amount rather
     * than routing through {@code receiveEnergy}'s maxReceive cap, purely
     * to remove energy availability as a variable in this specific test),
     * then lets {@link #PROGRESS_CHECK_DELAY_TICKS} real ticks pass and
     * checks the live {@code ContainerData} progress/active slots (index
     * 2/3) actually advanced - the one gap the energy-only sink tests
     * above intentionally left open (see their own doc: "reaching a non-
     * zero, deterministic progress value needs a valid queued recipe and
     * several ticks of processing... kept separate").
     */
    private static void assertMachineProgressAdvancesWhileProcessing(GameTestHelper helper,
            AbstractPrismiumMachineBlockEntity machine, Item inputItem, int inputCount, String label) {
        machine.getEnergyStorage().setEnergy(AbstractPrismiumMachineBlockEntity.CAPACITY);
        machine.getInventory().setStackInSlot(0, new ItemStack(inputItem, inputCount));

        helper.runAfterDelay(PROGRESS_CHECK_DELAY_TICKS, () -> {
            ContainerData containerData = machine.getContainerData();
            int progress = containerData.get(2);
            boolean active = containerData.get(3) != 0;

            helper.assertTrue(active,
                    label + " ContainerData slot 3 (active) was false after " + PROGRESS_CHECK_DELAY_TICKS
                            + " ticks with full energy and a valid queued recipe - processing appears stalled"
                            + " or the active-flag sync wiring is broken");
            helper.assertTrue(
                    progress >= PROGRESS_CHECK_DELAY_TICKS - PROGRESS_CHECK_SLACK_TICKS
                            && progress <= PROGRESS_CHECK_DELAY_TICKS,
                    label + " ContainerData slot 2 (progress) was " + progress + " after "
                            + PROGRESS_CHECK_DELAY_TICKS + " ticks, expected between "
                            + (PROGRESS_CHECK_DELAY_TICKS - PROGRESS_CHECK_SLACK_TICKS) + " and "
                            + PROGRESS_CHECK_DELAY_TICKS
                            + " (stuck at/near 0 means processing never started or the progress sync wiring is"
                            + " broken; a value above the upper bound would mean progress increments more than"
                            + " once per tick)");

            ItemStack remainingInput = machine.getInventory().getStackInSlot(0);
            helper.assertTrue(remainingInput.getCount() == inputCount,
                    label + " input slot count changed from " + inputCount + " to " + remainingInput.getCount()
                            + " after only " + PROGRESS_CHECK_DELAY_TICKS
                            + " ticks, before the operation should complete (PROCESS_TIME_TICKS="
                            + AbstractPrismiumMachineBlockEntity.PROCESS_TIME_TICKS
                            + ") - input consumed too early");

            helper.succeed();
        });
    }

    @GameTest(template = EMPTY_PLATFORM_TEMPLATE, templateNamespace = ClaudeMod.MOD_ID,
            timeoutTicks = PROGRESS_CHECK_DELAY_TICKS + 20)
    public static void pulverizerProgressAdvancesWhileProcessing(GameTestHelper helper) {
        BlockPos pos = new BlockPos(1, 1, 1);
        helper.setBlock(pos, ModBlocks.PRISMIUM_PULVERIZER.get());

        if (!(helper.getBlockEntity(pos) instanceof PrismiumPulverizerBlockEntity pulverizer)) {
            helper.fail("Pulverizer block entity was not created", pos);
            return;
        }

        // Pulverizer's recipe table (PrismiumPulverizerBlockEntity#recipes)
        // accepts the ore item directly; inputCountPerOperation() is not
        // overridden by Pulverizer, so it uses the base class default of 1
        // (see AbstractPrismiumMachineBlockEntity#inputCountPerOperation's
        // doc).
        assertMachineProgressAdvancesWhileProcessing(helper, pulverizer,
                ModItems.PRISMIUM_ORE_ITEM.get(), 1, "Pulverizer");
    }

    @GameTest(template = EMPTY_PLATFORM_TEMPLATE, templateNamespace = ClaudeMod.MOD_ID,
            timeoutTicks = PROGRESS_CHECK_DELAY_TICKS + 20)
    public static void smelterProgressAdvancesWhileProcessing(GameTestHelper helper) {
        BlockPos pos = new BlockPos(1, 1, 1);
        helper.setBlock(pos, ModBlocks.PRISMIUM_SMELTER.get());

        if (!(helper.getBlockEntity(pos) instanceof PrismiumSmelterBlockEntity smelter)) {
            helper.fail("Smelter block entity was not created", pos);
            return;
        }

        assertMachineProgressAdvancesWhileProcessing(helper, smelter, ModItems.PRISMIUM_SHARD.get(),
                PrismiumSmelterBlockEntity.SHARDS_PER_INGOT, "Smelter");
    }

    @GameTest(template = EMPTY_PLATFORM_TEMPLATE, templateNamespace = ClaudeMod.MOD_ID,
            timeoutTicks = PROGRESS_CHECK_DELAY_TICKS + 20)
    public static void compressorProgressAdvancesWhileProcessing(GameTestHelper helper) {
        BlockPos pos = new BlockPos(1, 1, 1);
        helper.setBlock(pos, ModBlocks.PRISMIUM_COMPRESSOR.get());

        if (!(helper.getBlockEntity(pos) instanceof PrismiumCompressorBlockEntity compressor)) {
            helper.fail("Compressor block entity was not created", pos);
            return;
        }

        assertMachineProgressAdvancesWhileProcessing(helper, compressor, ModItems.PRISMIUM_INGOT.get(),
                PrismiumCompressorBlockEntity.INGOTS_PER_ALLOY_INGOT, "Compressor");
    }
}
